### PR TITLE
Please use the new emailjs repos.

### PR DESCRIPTION
**Pull request by guettli**

### CODE REVIEW

**Comment by tanx** [comment]
Wrong github repo. The link is http://emailjs.org.

**Comment by guettli** [comment]
@tanx Have you looked at my pull-request? I want to update the README file to state exactly the same fact: use emailjs :-)

**Comment by tanx** [comment]
> @tanx Have you looked at my pull-request? I want to update the README file to state exactly the same fact: use emailjs :-)

Yeah. It's `(http://emailjs.org/)` not `(https://github.com/eleith/emailjs)`

**Comment by guettli** [comment]
I updated the pull request.

**Comment by tanx** [comment]
Thanks!

**Pull request merged**
